## Deliverable 2. Create a Customer Travel Destinations Map.

In [200]:
# Add the path of the sys.path file. 
sys.path.append('C:/Users/johnfortucci/class/WeatherPy')

# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import sys

sys.path
# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [201]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Khani,GE,41.96,42.96,26.17,78,100,1.77,Clouds
1,1,Qaanaaq,GL,77.48,-69.36,-7.44,98,100,0.49,Clouds
2,2,Desaguadero,PE,-16.57,-69.04,47.17,76,100,8.10,Clouds
3,3,Tiksi,RU,71.69,128.87,-16.80,99,98,1.36,Clouds
4,4,Rikitea,PF,-23.12,-134.97,80.29,71,100,14.36,Clouds

In [202]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 

# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("Enter the minimum temperature you would like for your trip? "))
max_temp = float(input("Enter is the maximum temperature you would like for your trip? "))

In [203]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
2,2,Desaguadero,PE,-16.57,-69.04,47.17,76,100,8.10,Clouds
4,4,Rikitea,PF,-23.12,-134.97,80.29,71,100,14.36,Clouds
5,5,Hilo,US,19.73,-155.09,78.53,72,100,12.66,Clouds
6,6,Bluff,NZ,-46.60,168.33,65.80,73,46,6.26,Clouds
7,7,Itoman,JP,26.12,127.67,75.58,75,75,4.61,Clouds
8,8,Sao Filipe,CV,14.90,-24.50,71.17,72,0,15.79,Clear
9,9,Bolitoc,PH,15.74,119.88,87.15,60,54,4.92,Clouds
10,10,Henties Bay,NaN,-22.12,14.28,62.82,90,96,10.51,Clouds
12,12,Price,US,39.60,-110.81,40.12,60,0,8.05,Clear
14,14,Ponta Do Sol,PT,32.67,-17.10,54.05,72,72,26.64,Clouds

In [204]:
# 4a. Determine if there are any empty rows.

preferred_cities_df.count()

City_ID                61
City                   61
Country                58
Lat                    61
Lng                    61
Max Temp               61
Humidity               61
Cloudiness             61
Wind Speed             61
Current Description    61
dtype: int64

In [205]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.

clean_df = preferred_cities_df.dropna(axis = 0, how ='any')
clean_df.count()

City_ID                58
City                   58
Country                58
Lat                    58
Lng                    58
Max Temp               58
Humidity               58
Cloudiness             58
Wind Speed             58
Current Description    58
dtype: int64

In [206]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)
hotel_df.count()

City                   58
Country                58
Max Temp               58
Current Description    58
Lat                    58
Lng                    58
Hotel Name             58
dtype: int64

In [207]:
# 6a. Set parameters to search for hotels with 5000 meters.
params =    {
            "radius": 5000,
            "type": "lodging",
            "key": g_key
            }           

# 6b. Iterate through the hotel DataFrame.
for index , row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]

    params["location"] = f"{lat},{lng}"
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        print(hotels["results"][0]["name"])
    except (IndexError):
        print("Hotel not found... skipping.")  
hotel_df.count()

inteeno hotel
People ThankYou
Hilo Hawaiian Hotel
Bluff Homestead - Guesthouse & Campervan Park
Southern Beach Hotel & Resort Okinawa
Hotel Xaguate
Seasun Beach Resort & Hotel
National 9 - Price River Inn
Hotel do Campo
Hampton Inn & Suites Jamestown
Hotel Hain
Chaleanor Hotel
Hotel not found... skipping.
Artemis Otel
Hotel Centrum Malbork
Keleti Beach Resort
The Mercury Motel
Ellie's Villa
Montra Skaga Hotel
Codrington Gardens Bed And Breakfast
Paradise Inn
Pazo de Verdes
Hótel Höfn
Hotel not found... skipping.
Nuevo Hotel Plaza
Moon light Furnished Units
Kaitangata Motor Camp
CHACARA BAILLY
Hotel Vila Galé Cascais
Cititel Penang
The Irish Village
Hostal Las Lilas
Albatross Hotel
Tanna Lodge
Westmark Sitka
Couvant des soeurs catholiques
Parra Hotel & Suites
Scenic Hotel Southern Cross
Hotel not found... skipping.
Casa Das Faias
Durrant House Hotel
SAFIR HOTEL
Southern Sun Waterfront Cape Town
Observatory Guest House
Blue Bay Lodge
St Ives Hobart Accommodation Tasmania
Soneva Fushi
Tarumã Tropical Hotel
Mercure Padang
Hotel y restaurante "El Diamante"
Red Lion Hotel Coos Bay
Hotel Castelo
Nancy Montanes Bernardo
The Shingles Riverside Cottages
Misty Waves Boutique Hotel
Pousada Divino Milagre
departamento comodo
Khách sạn Sài Gòn Bạc Liêu

City                   58
Country                58
Max Temp               58
Current Description    58
Lat                    58
Lng                    58
Hotel Name             58
dtype: int64

In [208]:
hotel_df.head(100)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Desaguadero,PE,47.17,Clouds,-16.57,-69.04,inteeno hotel
4,Rikitea,PF,80.29,Clouds,-23.12,-134.97,People ThankYou
5,Hilo,US,78.53,Clouds,19.73,-155.09,Hilo Hawaiian Hotel
6,Bluff,NZ,65.80,Clouds,-46.60,168.33,Bluff Homestead - Guesthouse & Campervan Park
7,Itoman,JP,75.58,Clouds,26.12,127.67,Southern Beach Hotel & Resort Okinawa
8,Sao Filipe,CV,71.17,Clear,14.90,-24.50,Hotel Xaguate
9,Bolitoc,PH,87.15,Clouds,15.74,119.88,Seasun Beach Resort & Hotel
12,Price,US,40.12,Clear,39.60,-110.81,National 9 - Price River Inn
14,Ponta Do Sol,PT,54.05,Clouds,32.67,-17.10,Hotel do Campo
15,Jamestown,US,32.02,Clouds,42.10,-79.24,Hampton Inn & Suites Jamestown
16,Punta Arenas,CL,41.11,Rain,-53.15,-70.92,Hotel Hain
17,Dangriga,BZ,75.85,Clouds,16.97,-88.23,Chaleanor Hotel
18,Gamba,GA,76.60,Rain,-2.65,10.00,
19,Erzin,TR,31.96,Clear,36.96,36.20,Artemis Otel
20,Marienburg,PL,33.57,Clear,54.04,19.03,Hotel Centrum Malbork
21,Vaini,TO,84.36,Clouds,-21.20,-175.20,Keleti Beach Resort
23,Atherton,GB,43.43,Clear,53.52,-2.49,The Mercury Motel
24,Mataura,NZ,65.48,Clouds,-46.19,168.86,Ellie's Villa
26,Hirtshals,DK,38.66,Clouds,57.59,9.96,Montra Skaga Hotel
27,Codrington,AU,76.24,Rain,-38.27,141.97,Codrington Gardens Bed And Breakfast
28,Avarua,CK,84.25,Clouds,-21.21,-159.78,Paradise Inn
29,Bereda,ES,40.57,Clouds,43.27,-7.54,Pazo de Verdes
31,Hofn,IS,34.79,Clear,64.25,-15.21,Hótel Höfn
32,Avera,US,38.91,Clear,33.19,-82.53,
33,Chuy,UY,60.30,Clear,-33.70,-53.46,Nuevo Hotel Plaza
34,Umm Lajj,SA,64.76,Clear,25.02,37.27,Moon light Furnished Units
35,Kaitangata,NZ,63.84,Clouds,-46.28,169.85,Kaitangata Motor Camp
36,Castro,BR,63.39,Clouds,-24.79,-50.01,CHACARA BAILLY
39,Cascais,PT,54.52,Clouds,38.70,-9.42,Hotel Vila Galé Cascais
40,Georgetown,MY,87.73,Clouds,5.41,100.34,Cititel Penang
41,Emerald,AU,86.14,Clouds,-23.53,148.17,The Irish Village
42,Lebu,CL,57.22,Clear,-37.62,-73.65,Hostal Las Lilas
43,Ushuaia,AR,38.86,Rain,-54.80,-68.30,Albatross Hotel
45,Isangel,VU,85.73,Clouds,-19.55,169.27,Tanna Lodge
46,Sitka,US,42.69,Clouds,57.05,-135.33,Westmark Sitka
48,Kambove,CD,58.62,Clouds,-10.88,26.60,Couvant des soeurs catholiques
49,Rafaela,AR,66.97,Clouds,-31.25,-61.49,Parra Hotel & Suites
50,Dunedin,NZ,65.80,Clouds,-45.87,170.50,Scenic Hotel Southern Cross
51,Tambo,PE,37.17,Clouds,-14.80,-73.92,
52,Lagoa,PT,55.26,Clouds,39.05,-27.98,Casa Das Faias
53,Northam,GB,42.26,Clouds,51.03,-4.22,Durrant House Hotel
54,Tchaourou,BJ,80.08,Clouds,8.89,2.60,SAFIR HOTEL
56,Cape Town,ZA,58.12,Clouds,-33.93,18.42,Southern Sun Waterfront Cape Town
57,Busselton,AU,75.70,Clouds,-33.65,115.33,Observatory Guest House
58,Saldanha,ZA,51.85,Clouds,-33.01,17.94,Blue Bay Lodge
59,Hobart,AU,64.26,Clouds,-42.88,147.33,St Ives Hobart Accommodation Tasmania
60,Eydhafushi,MV,82.33,Clouds,5.10,73.07,Soneva Fushi
61,Conceicao Do Araguaia,BR,73.22,Clear,-8.26,-49.26,Tarumã Tropical Hotel
62,Padang,ID,78.85,Clouds,-0.95,100.35,Mercure Padang
64,Champerico,GT,80.74,Clear,14.30,-91.92,"Hotel y restaurante ""El Diamante"""
65,North Bend,US,51.93,Clouds,43.41,-124.22,Red Lion Hotel Coos Bay
67,Cidreira,BR,69.75,Clouds,-30.18,-50.21,Hotel Castelo
68,Dicabisagan,PH,82.02,Clouds,17.08,122.42,Nancy Montanes Bernardo
69,New Norfolk,AU,63.90,Clouds,-42.78,147.06,The Shingles Riverside Cottages
70,Hermanus,ZA,51.80,Rain,-34.42,19.23,Misty Waves Boutique Hotel
71,Passo De Camaragibe,BR,78.35,Clouds,-9.24,-35.49,Pousada Divino Milagre
72,Talcahuano,CL,62.28,Clear,-36.72,-73.12,departamento comodo
73,Bac Lieu,VN,84.09,Clouds,9.29,105.72,Khách sạn Sài Gòn Bạc Liêu

In [209]:
# 7. Drop the rows where there is no Hotel Name.
print(hotel_df.count())

# clean_hotel_df = hotel_df.drop(hotel_df[hotel_df['Hotel Name'] == ''].index, inplace=True)
clean_hotel_df = hotel_df[hotel_df['Hotel Name'] != ""]
print(clean_hotel_df.head())
print(clean_hotel_df.count())

City                   58
Country                58
Max Temp               58
Current Description    58
Lat                    58
Lng                    58
Hotel Name             58
dtype: int64
          City Country  Max Temp Current Description    Lat     Lng  \
2  Desaguadero      PE     47.17              Clouds -16.57  -69.04
4      Rikitea      PF     80.29              Clouds -23.12 -134.97
5         Hilo      US     78.53              Clouds  19.73 -155.09
6        Bluff      NZ     65.80              Clouds -46.60  168.33
7       Itoman      JP     75.58              Clouds  26.12  127.67

                                      Hotel Name
2                                  inteeno hotel
4                                People ThankYou
5                            Hilo Hawaiian Hotel
6  Bluff Homestead - Guesthouse & Campervan Park
7          Southern Beach Hotel & Resort Okinawa
City                   55
Country                55
Max Temp               55
Current Description    55
Lat                    55
Lng                    55
Hotel Name             55
dtype: int64

In [210]:
print(os.getcwd())

c:\Users\johnfortucci\Class\WeatherPy\Vacation_search

In [211]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [214]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [215]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))